services:
    NetJan\ProductClientBundle\Controller\:
        resource: '../src/Controller/'
        autoconfigure: true
        autowire: true
        tags: ['controller.service_arguments']

    NetJan\ProductClientBundle\Repository\:
        resource: '../src/Repository/'
        autoconfigure: true
        autowire: true
        arguments: ['@eight_points_guzzle.client.netjan_product', '@validator']